name: Build and Test

on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.1', '8.8.3', '8.6.5', '8.4.4']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          - os: windows-latest
            ghc: '8.8.3' # fails due to segfault
          - os: macOS-latest
            ghc: '8.4.4' # fails due to ghc panic

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1.1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.2'
        enable-stack: true

    - name: Cache Cabal
      uses: actions/cache@v1.2.0
      with:
        path: ~/.cabal
        key: ${{ runner.OS }}-${{ matrix.ghc }}-cabal-0

    - run: cabal update
    - name: Build
      run: cabal build
    - name: Test
      run: cabal test

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: ludeeus/action-shellcheck@master
      with:
        ignore: tests
